# Generated by Django 5.1.4 on 2024-12-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Field_of_study',
            new_name='field_of_study',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='GPA',
            new_name='gpa',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_number',
            new_name='student_number',
        ),
    ]
